### ISSUE TITLE
1.0.4 fails to install (no such file README.rst)

### ISSUE THREAD

**Issue by ananelson** [monkeython/loremipsum#9]
I can't install version 1.0.4 via pip, see stack trace below. Running Python 2.7.6 on an Ubuntu docker image.

```
repro@9be8b20a54c0:~/orbiter$ sudo pip install loremipsum
Downloading/unpacking loremipsum
  Downloading loremipsum-1.0.4.tar.gz
  Running setup.py (path:/tmp/pip_build_root/loremipsum/setup.py) egg_info for package loremipsum
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/loremipsum/setup.py", line 16, in <module>
        with open('README.rst', 'r') as README:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/loremipsum/setup.py", line 16, in <module>

    with open('README.rst', 'r') as README:

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/loremipsum
Storing debug log for failure in /home/repro/.pip/pip.log
```

**Comment by monkeython** [comment]
Hi,
It should be fixed with 1.0.5

**Comment by polcar** [comment]
The 'dev' version (pip install --pre loremipsum) give version 1.0.5 bud still is affected by this issue. More precisely: what is missing is setup.py script.

**Comment by monkeython** [comment]
Will look into this. Thanks.

**Comment by monkeython** [comment]
Apparently the dumb binary package was messing up. I remove it from Pypi and now should insall correctly using the source distribution. Can you please try again?

**Comment by polcar** [comment]
I can confirm: it works. Thank you very much!

Jiri
